import type { Metadata } from "next";
import { Arvo, JetBrains_Mono, Recursive } from "next/font/google";

import { ThemeProvider } from "~/integration/next-themes/provider";
import { TanstackQueryProviders } from "~/integration/tanstack-query/provider";
import { cn } from "~/lib/utils";
import { Toaster } from "~/shadcn/ui/sonner";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"]
});

const arvo = Arvo({
  weight: ["400", "700"],
  variable: "--font-arvo",
  subsets: ["latin"]
});

const recursive = Recursive({
  variable: "--font-recursive",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={cn(
          jetbrainsMono.variable,
          arvo.variable,
          recursive.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="ui-theme"
        >
          <TanstackQueryProviders>
            {children}
            <Toaster position="top-right" />
          </TanstackQueryProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
